window.onload = function () {
  var globalStep = 0;
  var optionsSelected = {
    step1: "",
    step2: "",
    step3: "",
    step4: "",
    step5: "",
  };
  const btnRestart = document.getElementById("btnRestart");
  const resultado = document.getElementById("resultado");
  const resultadoValue = document.getElementById("resultadoValue");
  const steps = document.getElementsByClassName("step");

  const launchConfetti = () => {
    tsParticles.load("tsparticles", {
      fpsLimit: 60,
      particles: {
        number: {
          value: 0,
        },
        color: {
          value: ["#00FFFC", "#FC00FF", "#fffc00"],
        },
        shape: {
          type: "confetti",
          options: {
            confetti: {
              type: ["circle", "square"],
            },
          },
        },
        opacity: {
          value: 1,
          animation: {
            enable: true,
            minimumValue: 0,
            speed: 2,
            startValue: "max",
            destroy: "min",
          },
        },
        size: {
          value: 7,
          random: {
            enable: true,
            minimumValue: 3,
          },
        },
        links: {
          enable: false,
        },
        life: {
          duration: {
            sync: true,
            value: 5,
          },
          count: 1,
        },
        move: {
          enable: true,
          gravity: {
            enable: true,
            acceleration: 20,
          },
          speed: 20,
          decay: 0.1,
          direction: "none",
          random: false,
          straight: false,
          outModes: {
            default: "destroy",
            top: "none",
          },
        },
      },
      interactivity: {
        detectsOn: "window",
        events: {
          resize: true,
        },
      },
      detectRetina: true,
      background: {
        color: "#282c35",
      },
      emitters: {
        direction: "none",
        life: {
          count: 0,
          duration: 0.1,
          delay: 0.4,
        },
        rate: {
          delay: 0.1,
          quantity: 100,
        },
        size: {
          width: 0,
          height: 0,
        },
      },
    });
    document.getElementById("tsparticles").style.display = "block";
  };

  btnRestart.addEventListener("click", () => {
    globalStep = 0;
    optionsSelected = {
      step1: "",
      step2: "",
      step3: "",
      step4: "",
      step5: "",
    };
    checkDisplay(steps);
    document.getElementById("tsparticles").style.display = "none";
  });

  const checkDisplay = (steps) => {
    [...steps].forEach((step) => {
      console.log(step.id, `step${globalStep.toString()}`);
      if (globalStep === 6) {
        step.style.display = "none";
        const result = findAnswer();
        resultadoValue.innerText = result;
        resultado.style.display = "flex";
        launchConfetti();
      } else {
        if (step.id !== `step${globalStep.toString()}`) {
          step.style.display = "none";
        } else {
          step.style.display = "flex";
        }
      }
    });
  };

  checkDisplay(steps);

  [...steps].forEach((step) => {
    const options = step.getElementsByClassName("card");
    [...options].forEach((option) => {
      console.log(option.firstChild);
      option.addEventListener("click", function () {
        // console.log(this.getElementsByClassName("cardOption")[0]?.innerText);
        if (globalStep !== 0) {
          optionsSelected[`step${globalStep}`] =
            this.getElementsByClassName("cardOption")[0]?.innerText;
        }
        globalStep += 1;
        checkDisplay(steps);
        console.log(optionsSelected);
      });
    });
  });

  const findAnswer = () => {
    console.log(results, optionsSelected);
    return results.find(
      (res) =>
        res.step1 === optionsSelected.step1 &&
        res.step2 === optionsSelected.step2 &&
        res.step3 === optionsSelected.step3 &&
        res.step4 === optionsSelected.step4 &&
        res.step5 === optionsSelected.step5
    ).result;
  };

  var results = [
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "M",
      step5: "1",
      result: "Abejaruco",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "L",
      step5: "1",
      result: "Abadejo",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "S",
      step5: "1",
      result: "Abeja",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "M",
      step5: "2",
      result: "Abejorro",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "L",
      step5: "2",
      result: "Águila",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "S",
      step5: "2",
      result: "Albatros",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "M",
      step5: "3",
      result: "Alce",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "L",
      step5: "3",
      result: "Almeja",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "S",
      step5: "3",
      result: "Anchoa",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "M",
      step5: "4",
      result: "Anémona de mar",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "L",
      step5: "4",
      result: "Anguila",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "S",
      step5: "4",
      result: "Antílope",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "M",
      step5: "5",
      result: "Araña",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "L",
      step5: "5",
      result: "Arenque",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "S",
      step5: "5",
      result: "Armadillo",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "M",
      step5: "1",
      result: "Armiño",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "L",
      step5: "1",
      result: "Asno",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "S",
      step5: "1",
      result: "Atún",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "M",
      step5: "2",
      result: "Avefría",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "L",
      step5: "2",
      result: "Avestruz",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "S",
      step5: "2",
      result: "Avetoro",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "M",
      step5: "3",
      result: "Avispa",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "L",
      step5: "3",
      result: "Babosa",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "S",
      step5: "3",
      result: "Babuino",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "M",
      step5: "4",
      result: "Bacalao",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "L",
      step5: "4",
      result: "Ballena",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "S",
      step5: "4",
      result: "Beluga",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "M",
      step5: "5",
      result: "Bisonte",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "L",
      step5: "5",
      result: "Boa",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "S",
      step5: "5",
      result: "Buey",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "M",
      step5: "1",
      result: "Búfalo",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "L",
      step5: "1",
      result: "Búho",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "S",
      step5: "1",
      result: "Buitre",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "M",
      step5: "2",
      result: "Burro",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "L",
      step5: "2",
      result: "Caballo",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "S",
      step5: "2",
      result: "Caballito de mar",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "M",
      step5: "3",
      result: "Cacatúa",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "L",
      step5: "3",
      result: "Cachalote",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "S",
      step5: "3",
      result: "Camaleón",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "M",
      step5: "4",
      result: "Camello",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "L",
      step5: "4",
      result: "Canguro",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "S",
      step5: "4",
      result: "Canario",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "M",
      step5: "5",
      result: "Cangrejo",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "L",
      step5: "5",
      result: "Caracol",
    },
    {
      step1: "CHICO",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "S",
      step5: "5",
      result: "Castor",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "M",
      step5: "1",
      result: "Cebra",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "L",
      step5: "1",
      result: "Cerdo",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "S",
      step5: "1",
      result: "Chacal",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "M",
      step5: "2",
      result: "Chimpancé",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "L",
      step5: "2",
      result: "Ciempiés",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "S",
      step5: "2",
      result: "Ciervo",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "M",
      step5: "3",
      result: "Cigala",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "L",
      step5: "3",
      result: "Cisne",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "S",
      step5: "3",
      result: "Cobaya",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "M",
      step5: "4",
      result: "Cochinilla",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "L",
      step5: "4",
      result: "Cocodrilo",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "S",
      step5: "4",
      result: "Colibrí",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "M",
      step5: "5",
      result: "Comadreja",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "L",
      step5: "5",
      result: "Conejo",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "VERDE",
      step4: "S",
      step5: "5",
      result: "Cormorán",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "M",
      step5: "1",
      result: "Cóndor",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "L",
      step5: "1",
      result: "Cotorra",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "S",
      step5: "1",
      result: "Coyote\t",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "M",
      step5: "2",
      result: "Delfín",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "L",
      step5: "2",
      result: "Diablo de Tasmania",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "S",
      step5: "2",
      result: "Dingo",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "M",
      step5: "3",
      result: "Dragón de Komodo",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "L",
      step5: "3",
      result: "Dromedario",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "S",
      step5: "3",
      result: "Elefante",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "M",
      step5: "4",
      result: "Emú",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "L",
      step5: "4",
      result: "Ratón",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "S",
      step5: "4",
      result: "Serpiente",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "M",
      step5: "5",
      result: "Jaguar",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "L",
      step5: "5",
      result: "Erizo",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "ROJO",
      step4: "S",
      step5: "5",
      result: "Escarabajo",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "M",
      step5: "1",
      result: "Escorpión",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "L",
      step5: "1",
      result: "Espátula común",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "S",
      step5: "1",
      result: "Estrella de mar",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "M",
      step5: "2",
      result: "Faisán",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "L",
      step5: "2",
      result: "Flamenco",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "S",
      step5: "2",
      result: "Koala",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "M",
      step5: "3",
      result: "Foca",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "L",
      step5: "3",
      result: "Perro",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "S",
      step5: "3",
      result: "Gacela",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "M",
      step5: "4",
      result: "Pulpo",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "L",
      step5: "4",
      result: "Galápago",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "S",
      step5: "4",
      result: "Gallina",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "M",
      step5: "5",
      result: "Gallo",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "L",
      step5: "5",
      result: "Gamba",
    },
    {
      step1: "CHICA",
      step2: "ANIMALES",
      step3: "AMARILLO",
      step4: "S",
      step5: "5",
      result: "Golondrina",
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "VERDE",
      step4: "M",
      step5: "1",
      result: 13,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "VERDE",
      step4: "L",
      step5: "1",
      result: 80,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "VERDE",
      step4: "S",
      step5: "1",
      result: 7,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "VERDE",
      step4: "M",
      step5: "2",
      result: 58,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "VERDE",
      step4: "L",
      step5: "2",
      result: 8,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "VERDE",
      step4: "S",
      step5: "2",
      result: 16,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "VERDE",
      step4: "M",
      step5: "3",
      result: 93,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "VERDE",
      step4: "L",
      step5: "3",
      result: 15,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "VERDE",
      step4: "S",
      step5: "3",
      result: 68,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "VERDE",
      step4: "M",
      step5: "4",
      result: 21,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "VERDE",
      step4: "L",
      step5: "4",
      result: 66,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "VERDE",
      step4: "S",
      step5: "4",
      result: 0,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "VERDE",
      step4: "M",
      step5: "5",
      result: 27,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "VERDE",
      step4: "L",
      step5: "5",
      result: 17,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "VERDE",
      step4: "S",
      step5: "5",
      result: 56,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "ROJO",
      step4: "M",
      step5: "1",
      result: 50,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "ROJO",
      step4: "L",
      step5: "1",
      result: 16,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "ROJO",
      step4: "S",
      step5: "1",
      result: 61,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "ROJO",
      step4: "M",
      step5: "2",
      result: 95,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "ROJO",
      step4: "L",
      step5: "2",
      result: 95,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "ROJO",
      step4: "S",
      step5: "2",
      result: 41,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "ROJO",
      step4: "M",
      step5: "3",
      result: 97,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "ROJO",
      step4: "L",
      step5: "3",
      result: 4,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "ROJO",
      step4: "S",
      step5: "3",
      result: 83,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "ROJO",
      step4: "M",
      step5: "4",
      result: 18,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "ROJO",
      step4: "L",
      step5: "4",
      result: 91,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "ROJO",
      step4: "S",
      step5: "4",
      result: 77,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "ROJO",
      step4: "M",
      step5: "5",
      result: 0,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "ROJO",
      step4: "L",
      step5: "5",
      result: 47,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "ROJO",
      step4: "S",
      step5: "5",
      result: 93,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "M",
      step5: "1",
      result: 48,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "L",
      step5: "1",
      result: 82,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "S",
      step5: "1",
      result: 6,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "M",
      step5: "2",
      result: 35,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "L",
      step5: "2",
      result: 38,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "S",
      step5: "2",
      result: 71,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "M",
      step5: "3",
      result: 70,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "L",
      step5: "3",
      result: 65,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "S",
      step5: "3",
      result: 77,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "M",
      step5: "4",
      result: 86,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "L",
      step5: "4",
      result: 54,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "S",
      step5: "4",
      result: 51,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "M",
      step5: "5",
      result: 0,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "L",
      step5: "5",
      result: 95,
    },
    {
      step1: "CHICO",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "S",
      step5: "5",
      result: 19,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "VERDE",
      step4: "M",
      step5: "1",
      result: 88,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "VERDE",
      step4: "L",
      step5: "1",
      result: 18,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "VERDE",
      step4: "S",
      step5: "1",
      result: 83,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "VERDE",
      step4: "M",
      step5: "2",
      result: 27,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "VERDE",
      step4: "L",
      step5: "2",
      result: 35,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "VERDE",
      step4: "S",
      step5: "2",
      result: 66,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "VERDE",
      step4: "M",
      step5: "3",
      result: 65,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "VERDE",
      step4: "L",
      step5: "3",
      result: 91,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "VERDE",
      step4: "S",
      step5: "3",
      result: 69,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "VERDE",
      step4: "M",
      step5: "4",
      result: 10,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "VERDE",
      step4: "L",
      step5: "4",
      result: 20,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "VERDE",
      step4: "S",
      step5: "4",
      result: 84,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "VERDE",
      step4: "M",
      step5: "5",
      result: 93,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "VERDE",
      step4: "L",
      step5: "5",
      result: 54,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "VERDE",
      step4: "S",
      step5: "5",
      result: 93,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "ROJO",
      step4: "M",
      step5: "1",
      result: 92,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "ROJO",
      step4: "L",
      step5: "1",
      result: 3,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "ROJO",
      step4: "S",
      step5: "1",
      result: 29,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "ROJO",
      step4: "M",
      step5: "2",
      result: 5,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "ROJO",
      step4: "L",
      step5: "2",
      result: 2,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "ROJO",
      step4: "S",
      step5: "2",
      result: 90,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "ROJO",
      step4: "M",
      step5: "3",
      result: 76,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "ROJO",
      step4: "L",
      step5: "3",
      result: 41,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "ROJO",
      step4: "S",
      step5: "3",
      result: 50,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "ROJO",
      step4: "M",
      step5: "4",
      result: 98,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "ROJO",
      step4: "L",
      step5: "4",
      result: 13,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "ROJO",
      step4: "S",
      step5: "4",
      result: 38,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "ROJO",
      step4: "M",
      step5: "5",
      result: 14,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "ROJO",
      step4: "L",
      step5: "5",
      result: 27,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "ROJO",
      step4: "S",
      step5: "5",
      result: 88,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "M",
      step5: "1",
      result: 36,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "L",
      step5: "1",
      result: 16,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "S",
      step5: "1",
      result: 65,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "M",
      step5: "2",
      result: 25,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "L",
      step5: "2",
      result: 83,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "S",
      step5: "2",
      result: 64,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "M",
      step5: "3",
      result: 27,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "L",
      step5: "3",
      result: 62,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "S",
      step5: "3",
      result: 27,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "M",
      step5: "4",
      result: 28,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "L",
      step5: "4",
      result: 27,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "S",
      step5: "4",
      result: 87,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "M",
      step5: "5",
      result: 12,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "L",
      step5: "5",
      result: 59,
    },
    {
      step1: "CHICA",
      step2: "DINERO",
      step3: "AMARILLO",
      step4: "S",
      step5: "5",
      result: 41,
    },
  ];
};
